scopes:

    group:
        label     : blakejones.magicforms::lang.controllers.records.columns.group
        type      : group
        modelClass: BlakeJones\MagicForms\Models\Record
        options   : filterGroups
        conditions: "`group` in (:filtered)"

    created_at:
        label     : blakejones.magicforms::lang.controllers.records.columns.created_at
        type      : daterange
        conditions: created_at >= ':after' AND created_at <= ':before'